name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 18
      - name: yarn
        run: yarn --frozen-lockfile
      - name: flow
        run: yarn run flow
      - name: test
        run: yarn run test
      - name: build
        run: yarn run build

  publish:
    needs: test
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
          scope: '@joyep-tzt'
      - name: yarn
        run: yarn --frozen-lockfile
      - name: build
        run: yarn run build
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
