# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 18
      - name: yarn
        run: yarn --frozen-lockfile
      - name: flow
        run: yarn run flow
      - name: test
        run: yarn run test
      - name: build
        run: yarn run build

  publish:
    needs: test
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
          scope: '@joyep-tzt'
      - name: yarn
        run: yarn --frozen-lockfile
      - name: build
        run: yarn run build
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
